evaluacion2_PasteleriaDulceKapricho/Controllers/DulceKaprichoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace evaluacion2_PasteleriaDulceKapricho.Controllers
{
    public class DulceKaprichoController : Controller
    {
        private string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=bddEva3;Integrated Security=True;Connect Timeout=30;";

        public class Persona
        {
            public string RUT { get; set; }
            public string NOMBRE { get; set; }
            public string APELLIDO { get; set; }
            public string CORREO { get; set; }
            public string CLAVE { get; set; }
            public DateTime F_NACIMIENTO { get; set; }
            public string DIRECCION { get; set; }
            public int TELEFONO { get; set; }
            public int NIVEL { get; set; }
        }
        public class Producto
        {
            public int ID_PRODUCTO { get; set; }
            public string NOMBRE_PRODUCTO { get; set; }
            public int ID_MATERIA { get; set; }
            public string CATEGORIA { get; set; }
            public int STOCK { get; set; }
            public int COSTO { get; set; }
            public int PRECIO { get; set; }
        }
        public class Compra
        {
            public int N_COMPRA { get; set; }
            public string RUT_PROVEEDOR { get; set; }
            public int ID_MATERIA { get; set; }
            public int CANTIDAD { get; set; }
            public int PRECIO { get; set; }
            public DateTime FECHA_COMPRA { get; set; }
        }
        public class Delivery
        {
            public int IdDelivery { get; set; }
            public string RutDelivery { get; set; }
            public string NombreDelivery { get; set; }
            public DateTime FechaPedido { get; set; }
        }
        public IActionResult LoginTrabajador()
        {
            return View("/Views/DulceKapricho/Trabajador/login.cshtml");
        }
        public IActionResult LoginCliente()
        {
            return View("/Views/DulceKapricho/Clientes/LoginCliente.cshtml");
        }
        public IActionResult LoginAdmin()
        {
            return View("/Views/DulceKapricho/Trabajador/admin.cshtml");
        }
        public IActionResult PortalAdmin()
        {
            return View("/Views/DulceKapricho/Trabajador/portalAdministrador.cshtml");
        }
        public IActionResult CrearTrabajador()
        {
            return View("/Views/DulceKapricho/Trabajador/crearTrabajador.cshtml");
        }
        public IActionResult RegistrarCliente()
        {
            return View("/Views/DulceKapricho/Clientes/registrarCliente.cshtml");
        }
        public IActionResult Contacto()
        {
            return View("/Views/DulceKapricho/Clientes/contacto.cshtml");
        }
        public IActionResult CrearProducto()
        {
            List<Producto> productos = new List<Producto>();

            string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=bddEva3;Integrated Security=True;Connect Timeout=30;";
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                var sentencia = new SqlCommand();
                sentencia.CommandType = System.Data.CommandType.Text;
                string query = "SELECT * FROM PRODUCTOS";
                SqlCommand cmd = new SqlCommand(query, con);
                SqlDataReader reader = cmd.ExecuteReader();
                string htmlProductos = "";
                while (reader.Read())
                {
                    htmlProductos += $"<tr><td>{reader["ID_PRODUCTO"]}</td><td>{reader["NOMBRE_PRODUCTO"]}</td><td>{reader["ID_MATERIA"]}</td><td>{reader["CATEGORIA"]}</td><td>{reader["STOCK"]}</td><td>{reader["COSTO"]}</td><td>{reader["PRECIO"]}</td></tr>";
                }
                ViewBag.htmlProductos = htmlProductos;
                con.Close();
            }
            return View("/Views/DulceKapricho/Productos/crearProducto.cshtml");
        }
        public IActionResult VerProductos()
        {
            return View("/Views/DulceKapricho/Productos/Productos.cshtml");
        }

        public IActionResult PortalTrabajador()
        {
            return View("/Views/DulceKapricho/Trabajador/portalTrabajador.cshtml");
        }
        public IActionResult PortalAdministrador()
        {
            return View("/Views/DulceKapricho/Trabajador/portalAdministrador.cshtml");
        }
        public IActionResult PortalClientes()
        {
            return View("/Views/Home/Index.cshtml");
        }
        public IActionResult Despacho()
        {
            return View("/Views/DulceKapricho/Despacho/despacho.cshtml");
        }
        public IActionResult PedidosPendientes()
        {
            return View("/Views/DulceKapricho/Despacho/pedidosPendientes.cshtml");
        }
        public IActionResult Portales()
        {
            return View("/Views/DulceKapricho/portales.cshtml");
        }
        public IActionResult Tipo()
        {
            return View("/Views/DulceKapricho/bifurcacion.cshtml");
        }
        public IActionResult Stock()
        {
            return View("/Views/DulceKapricho/Stock/portalStock.cshtml");
        }
        public IActionResult StockTrabajador()
        {
            return View("/Views/DulceKapricho/Stock/portalStockTrabajador.cshtml");
        }
        public IActionResult AddMaterial()
        {
            List<string> materiaPrima = new List<string>();

            string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=bddEva3;Integrated Security=True;Connect Timeout=30;";
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                var sentencia = new SqlCommand();
                sentencia.CommandType = System.Data.CommandType.Text;
                string query = "SELECT * FROM MATERIA_PRIMA";
                SqlCommand cmd = new SqlCommand(query, con);
                SqlDataReader reader = cmd.ExecuteReader();
                string htmlMateriaPrima = "";
                while (reader.Read())
                {
                    htmlMateriaPrima += $"<tr><td>{reader["ID_MATERIA"]}</td><td>{reader["RUT_PROVEEDOR"]}</td><td>{reader["CANTIDAD"]}</td><td>{reader["FECHA"]}</td><td>{reader["NOMBRE_MATERIAL"]}</td></tr>";
                }
                ViewBag.htmlMateriaPrima = htmlMateriaPrima;
                con.Close();
            }
            return View("/Views/DulceKapricho/Stock/agregarMateria.cshtml");
        }
        public IActionResult SolicitarMateria()
        {

            return View("/Views/DulceKapricho/Stock/solicitarMateria.cshtml");
        }
        public IActionResult Carrito()
        {
            return View("/Views/DulceKapricho/Productos/Carrito.cshtml");
        }
        public IActionResult Compras()
        {
            List<Compra> compras = new List<Compra>();

            string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=bddEva3;Integrated Security=True;Connect Timeout=30;";
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                var sentencia = new SqlCommand();
                sentencia.CommandType = System.Data.CommandType.Text;
                string query = "SELECT * FROM COMPRAS";
                SqlCommand cmd = new SqlCommand(query, con);
                SqlDataReader reader = cmd.ExecuteReader();
                string htmlCompras = "";
                while (reader.Read())
                {
                    htmlCompras += $"<tr><td>{reader["N_COMPRA"]}</td><td>{reader["RUT_PROVEEDOR"]}</td><td>{reader["ID_MATERIA"]}</td><td>{reader["CANTIDAD"]}</td><td>{reader["PRECIO"]}</td><td>{reader["FECHA_COMPRA"]}</td></tr>";
                }
                ViewBag.htmlCompras = htmlCompras;
                con.Close();
            }
            return View("/Views/DulceKapricho/Administrador/compras.cshtml");
        }
        public IActionResult delivery()
        {
            {
                List<string> personas = new List<string>();

                string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=bddEva3;Integrated Security=True;Connect Timeout=30;";
                using (SqlConnection con = new SqlConnection(connectionString))
                {
                    con.Open();
                    var sentencia = new SqlCommand();
                    sentencia.CommandType = System.Data.CommandType.Text;
                    string query = "SELECT * FROM PERSONA WHERE NIVEL = 4";
                    SqlCommand cmd = new SqlCommand(query, con);
                    SqlDataReader reader = cmd.ExecuteReader();
                    string htmlPersona = "";
                    while (reader.Read())
                    {
                        htmlPersona += $"<tr><td>{reader["RUT"]}</td><td>{reader["NOMBRE"]}</td><td>{reader["APELLIDO"]}</td><td>{reader["CORREO"]}</td><td>{reader["CLAVE"]}</td><td>{reader["F_NACIMIENTO"]}</td><td>{reader["DIRECCION"]}</td><td>{reader["TELEFONO"]}</td><td>{reader["NIVEL"]}</td></tr>";
                    }
                    ViewBag.htmlPersona = htmlPersona;
                    con.Close();
                }

                return View("/Views/DulceKapricho/Administrador/delivery.cshtml");
            }
        }

        public IActionResult DeliveryForm()
        {
            List<string> deliveries = new List<string>();

            string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=bddEva3;Integrated Security=True;Connect Timeout=30;";
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                con.Open();
                var sentencia = new SqlCommand();

evaluacion2_PasteleriaDulceKapricho/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pasteleria Dulce Kapricho</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/evaluacion2_PasteleriaDulceKapricho.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="DulceKapricho" asp-action="Login">evaluacion2_PasteleriaDulceKapricho</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DulceKapricho" asp-action="VerLogin">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - evaluacion2_PasteleriaDulceKapricho - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>